posters/posters/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.conf import settings
import debug_toolbar
# NOTE: Add in production!
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    # NOTE: Uncomment in production!
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    # path('posters/', include(('posters_app.urls', 'posters_app'), namespace='posters_app')),
    # path('user_account/', include(('user_account_app.urls', 'user_account_app'), namespace='user_account_app')),
    path('i18n/', include('django.conf.urls.i18n')),
    # path('user_auth/', include("django.contrib.auth.urls")),
]


urlpatterns += i18n_patterns (
    path('posters/', include(('posters_app.urls', 'posters_app'), namespace='posters_app')),
    path('user_account/', include(('user_account_app.urls', 'user_account_app'), namespace='user_account_app')),
)

# NOTE: Comment in Production!
if settings.DEBUG:
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

posters/posters_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('categories/', views.PosterCategoriesView.as_view(), name='categories'),
    path('all/<str:category_name>', views.CategoryView.as_view(), name='list_posters_in_category'),
    path('create_poster/', views.create_poster, name='create_poster'),
    path('poster/<int:poster_id>/edit', views.edit_poster, name='edit_poster'),
    path('poster/<int:poster_id>/delete', views.delete_poster_by_id, name='delete_poster_by_id'),
    path('user_posters/<int:user_id>', views.create_poster, name='user_posters'),
    path('poster/<int:poster_id>', views.PosterView.as_view(), name='poster_view'),
    path('get_poster_image/<slug:image_id>', views.get_image_by_image_id, name='get_image_by_image_id'),
    # path('get_poster_image/', views.get_image_by_image_id, {'image_id': None}, name='get_default_image'),
    path('get_poster_image/<path:image_path>', views.get_image_by_image_path, name='get_image_by_image_path')
]

posters/posters_app/forms.py
from django import forms
from django.forms import inlineformset_factory, modelformset_factory
from .models import Poster, PosterImages


class CreatePosterForm(forms.ModelForm):
    class Meta:
        model = Poster
        fields = ['header', 'description', 'phone_number',
                  'email', 'category', 'price', 'currency']


# Creating a poster add images.
PosterImageFormSet = inlineformset_factory(
    Poster, PosterImages,
    fields=('image_path', ),
    # BUG: When extra variable is set and multiple forms managed by JS are used. Forms upload only one picture.
    # extra=1, # Num of forms to display #NOTE: (disable when use multiple forms manages by JS).
    can_delete=True  # Allow users delete images.
)


class PosterImageForm(forms.ModelForm):
    class Meta:
        model = PosterImages
        fields = ['image_path']


EditPosterImageFormSet = modelformset_factory(
    PosterImages,
    form=PosterImageForm,
    extra=0,  # Number of empty forms to display for new images
    can_delete=True  # This allows users to delete images
)


class EditPosterForm(forms.ModelForm):
    class Meta:
        model = Poster
        fields = ['header', 'description', 'phone_number',
                  'email', 'category', 'price', 'currency']


class SearchForm(forms.Form):
    query = forms.CharField(label='Search', max_length=255)

posters/posters_app/views.py
from typing_extensions import Any, Generator
from django.db.models.query import QuerySet
from django.shortcuts import get_object_or_404, redirect, render, HttpResponse
from django.views.generic import TemplateView, ListView

from django.urls import reverse
from django.core.cache import cache
from django.views.decorators.cache import never_cache, cache_control
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, Page
from django.core.cache import cache
from django.utils.translation import gettext as _

from .models import Poster, PosterImages
from .forms import CreatePosterForm, PosterImageFormSet, EditPosterForm, SearchForm, EditPosterImageFormSet
from .business_logic.view_logic import FrequentQueries, SearchQueryEngine
from .business_logic.process_images_logic import (
    get_image_by_image_id_response,
    get_image_by_image_path_response,
    process_formset_with_images_for_model)

# CACHE VARIABLES
from .constants import (
    RECOMMENDED_POSTERS_CACHE_KEY,
    CATEGORIES_CACHE_KEY
)


class HomePageView(TemplateView):
    template_name = 'posters_app/index.html'

    def __init__(self, **kwargs: Any) -> None:
        self.recommended_posters = FrequentQueries.get_recommended_posters()
        super().__init__(**kwargs)

    def get_page(self, queryset: QuerySet, chunk_size: int, page_number: int) -> Page:
        """
        Makes a page for displaying QuerySet elements by chunks 
        in pages using Django built-in pagination tool.
        :Param queryset: Set of posters.
        :Param chunk_size: Number of element (posters) on the page.
        :Param page number: Page number. E.g. '?page=1'.
        """
        paginator = Paginator(queryset, chunk_size)
        page_obj = paginator.get_page(page_number)

        return page_obj

    def smart_pagination(self, page_number: int, chunk_size: int, search: QuerySet | None) -> Page:
        """
        Paginate home page with the default QuerySet, when search is used, paginate the
        filtered default QuerySey (search results).
        :Param page_number: Chosen page number (required for pagination).
        :Param chuck_size: Number of items per page (required for pagination).
        :Param search: A QuerySet of keywords (required for searching (filtering)). 
        """
        if search:
            search_result = SearchQueryEngine.apply_search_filter(
                self.recommended_posters, search)
            return self.get_page(search_result, chunk_size, page_number)

        return self.get_page(self.recommended_posters, chunk_size, page_number)

    def chucked(self, queryset: QuerySet, chuck_size: int) -> Generator[QuerySet]:
        for i in range(0, len(queryset), chuck_size):
            yield queryset[i:i + chuck_size]

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['recommended_posters_row'] = self.chucked(
            self.recommended_posters, 3)
        context['page_obj'] = self.smart_pagination(
            self.request.GET.get('page'), 9,
            self.request.GET.get('query')
        )
        context['form'] = SearchForm()

        return context


class PosterCategoriesView(TemplateView):
    template_name = 'posters_app/categories.html'

    def get_queryset(self):
        # Cache
        # NOTE: Invalidate when a new category or poster is created.
        return FrequentQueries.get_poster_categories_w_count()

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['categories'] = self.get_queryset()
        return context


class CategoryView(ListView):
    """View all posters in category <str:category_name> with optional search."""

    template_name = 'posters_app/category.html'
    context_object_name = 'posters'
    model = Poster
    paginate_by = 10

    def get_queryset(self) -> QuerySet[Any]:
        """Retrieve posters by category, with optional search filtering."""

        category_name = self.kwargs.get('category_name')
        # NOTE: DO not use cache or write validation for it.
        queryset = FrequentQueries.get_posters_in_category(
            category_name=category_name)
        # Apply search filter if a search query is present
        search_query = self.request.GET.get('query')
        return SearchQueryEngine.apply_search_filter(queryset, search_query)

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        """Add extra context data for the category and search form."""

        context = super().get_context_data(**kwargs)
        context['form'] = SearchForm()
        context['category_name'] = self.kwargs.get('category_name')
        return context


class PosterView(TemplateView):
    template_name = 'posters_app/poster.html'

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        poster_id = kwargs.get('poster_id')
        poster = FrequentQueries.get_active_poster(poster_id=poster_id)
        context['poster'] = poster
        context['user'] = self.request.user
        return context


@login_required
def create_poster(request):
    success_url = reverse('posters_app:home')
    if request.method == "POST":
        form = CreatePosterForm(request.POST)
        formset = PosterImageFormSet(request.POST, request.FILES)
        if form.is_valid() and formset.is_valid():
            poster = form.save(commit=False)
            poster.owner = request.user
            poster.save()

            process_formset_with_images_for_model(
                formset=formset,
                instance=poster,
                related_field='poster_images',
                image_model=PosterImages
            )

            # Cache validation
            cache.delete(RECOMMENDED_POSTERS_CACHE_KEY)
            cache.delete(CATEGORIES_CACHE_KEY)

            return redirect(success_url)
        else:
            print(f'[DEBUG] FORMSET ERRORS: {formset.errors}')
            print(f'[DEBUG] FORM ERRORS: {form.errors}')
    else:
        form = CreatePosterForm()
        formset = PosterImageFormSet()

    return render(request, 'posters_app/create_poster.html', {'form': form, 'formset': formset})


@never_cache
@login_required
def delete_poster_by_id(request, poster_id: int):
    poster = get_object_or_404(Poster, id=poster_id)

    if poster.owner != request.user:
        return HttpResponse(f"Not your poster")

    poster_images = PosterImages.objects.filter(poster_id=poster_id)

    for poster_image in poster_images:
        poster_image.delete()

    poster.delete()
    # Cache validation
    cache.delete(RECOMMENDED_POSTERS_CACHE_KEY)
    cache.delete(CATEGORIES_CACHE_KEY)

    return redirect('posters_app:home')


# NOTE: Only owner can edit its post.
@login_required
def edit_poster(request, poster_id: int):
    success_url = reverse('posters_app:poster_view', args=(poster_id,))
    poster = get_object_or_404(Poster, id=poster_id)
    poster_images = PosterImages.objects.filter(poster_id=poster)

    if poster.owner != request.user:
        return HttpResponse("Cannot edit someone else's poster!")

    if request.method == 'POST':
        form = EditPosterForm(request.POST, instance=poster)
        formset = EditPosterImageFormSet(
            request.POST, request.FILES, queryset=poster_images)

        if formset.total_form_count() > 10:
            formset._non_form_errors = formset.error_class(
                _['You can upload a maximum of 10 images.'])

        if form.is_valid() and formset.is_valid():
            form.save()

            process_formset_with_images_for_model(
                formset=formset,
                instance=poster,
                related_field='poster_images',
                image_model=PosterImages
            )

            return redirect(success_url)
        else:
            print(f'[DEBUG] FORMSET ERRORS: {formset.errors}')
            print(f'[DEBUG] FORM ERRORS: {form.errors}')
    else:
        form = EditPosterForm(instance=poster)
        formset = EditPosterImageFormSet(queryset=poster_images)

    return render(request, 'posters_app/edit_poster.html', {'form': form, 'formset': formset})


@cache_control(max_age=15)
def get_image_by_image_id(request, image_id: int | None):
    return get_image_by_image_id_response(image_id)


def get_image_by_image_path(request, image_path):
    return get_image_by_image_path_response(image_path)

posters/posters_app/templates/posters_app/categories.html
{% extends 'posters_base.html' %}
{% load i18n %}
{% block title %} {% trans "Categories" %} {% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'posters_app/css/categories.css'%}">
<script src="{% static 'posters_app/js/categories.js'%}" type="text/javascript"></script>

<div class="container">
    <h1>{% trans "Categories:" %}</h1>
    <ul class="list-group">
        {% for category in categories %}
        <li class="list-group-item"> <span class="badge"> {{ category.posters_in_category}} </span>
            <a href="{% url 'posters_app:list_posters_in_category' category.name %}"> {{ category }}</a>
        </li>
        {% endfor %}
      </ul>



    {% comment %} <ul>
        {% for category in categories %}
        <div class="container-fluid">
            <li>
                <h3>
                    <a href="{% url 'posters_app:list_posters_in_category' category.name %}"> <i class="fa fa-laptop" aria-hidden="true"></i> {{ category }}</a>
                </h3>
            </li>
        </div>
        {% endfor %}
    </ul> {% endcomment %}
</div>

{% endblock %}

posters/posters_app/templates/posters_app/category.html
{% extends 'posters_base.html' %}
{% load i18n %}
{% block title %} {% trans "Categories" %} {% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'posters_app/css/category.css'%}">
<script src="{% static 'posters_app/js/category.js'%}" type="text/javascript"></script>

<div class="container">
    <div class="container-fluid" id="search-bar">
        <h4>{% trans "Search posters" %}</h4>
        <form method="get" action="{% url 'posters_app:list_posters_in_category' category_name %}">
            {{ form.query.label_tag }}
            {{ form.query }}
            <button type="submit">{% trans "Search" %}</button>
        </form>
    </div>
    <h1>{% trans "All posters:" %}</h1>
    <ul class="list-group">
        {% for poster in posters %}
        <a href="{% url 'posters_app:poster_view' poster.id %}">
            <li class="list-group-item">
                <div class="container-fluid">
                    <h3 id="posterHeader"> {{ poster.header }} </h3>
                    <p id="posterDescription"> {{ poster.formatted_created }} </p>
                    <p id="posterPrice"> {{ poster.price_rounded }} {{ poster.currency }} </p>
                    <img src="{% url 'posters_app:get_image_by_image_id' poster.image_ids.0 %}" alt="Image">
                </div>
            </li>
        </a>    
        {% endfor %}
    </ul>
</div>

{% endblock %}

posters/posters_app/templates/posters_app/create_poster.html
{% extends 'posters_base.html' %}
{% load i18n %}
{% block title %}{% trans "Create poster" %}{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
{% load static %}
<link rel="stylesheet" href="{% static 'posters_app/css/create_poster.css' %}">
<script src="{% static 'posters_app/js/create_poster.js' %}" type="text/javascript"></script>

<div class="container" id="create_poster">
    <h1>{% trans "Create new poster" %}</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}

        <div id="image-formset">
            {{ formset.management_form }}
            {% for form in formset %}
                <div class="form-row">
                    {{ form.image_path.label_tag }} {{ form.image_path }}
                    <a href="#" class="remove-form-row">{% trans "Remove" %}</a>
                </div>
            {% endfor %}
        </div>

        <button type="button" id="add-form-row">{% trans "Add image" %}</button>
        <button type="submit" class="btn btn-success" >{% trans "Save poster" %}</button>
    </form>
</div>

{% comment %} <script>
    document.addEventListener('DOMContentLoaded', function () {
        var formset = document.getElementById('image-formset');
        var addButton = document.getElementById('add-form-row');
        var totalFormsInput = formset.querySelector('input[name$="TOTAL_FORMS"]');  // Using a more flexible selector

        if (!totalFormsInput) {
            console.error("Management form 'TOTAL_FORMS' input not found.");
            return;
        }

        addButton.addEventListener('click', function () {
            var formCount = parseInt(totalFormsInput.value);
            var newForm = formset.querySelector('.form-row:last-child').cloneNode(true);

            // Clear values in the cloned form
            Array.from(newForm.querySelectorAll('input')).forEach(function (input) {
                input.value = '';
                // Update the name and id to the new form count
                var name = input.name.replace(/form-(\d+)-/, 'form-' + formCount + '-');
                var id = input.id.replace(/form-(\d+)-/, 'form-' + formCount + '-');
                input.name = name;
                input.id = id;
            });

            // Append the new form to the formset
            formset.appendChild(newForm);

            // Increment the total number of forms
            totalFormsInput.value = formCount + 1;
        });

        formset.addEventListener('click', function (e) {
            if (e.target.classList.contains('remove-form-row')) {
                e.preventDefault();

                // Only remove if there's more than one form remaining
                if (formset.querySelectorAll('.form-row').length > 1) {
                    e.target.parentNode.remove();
                    // Decrement the total number of forms
                    totalFormsInput.value = parseInt(totalFormsInput.value) - 1;
                }
            }
        });
    });
</script> {% endcomment %}
{% endblock %}

posters/posters_app/templates/posters_app/index.html
{% extends 'posters_base.html' %}
{% load i18n %}
{% block title %} {% trans "Posters" %} {% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'posters_app/css/index.css'%}">
<script src="{% static 'posters_app/js/index.js'%}" type="text/javascript"></script>


<div class="container">
    <div class="container-fluid" id="search-bar">
        <h4>{% trans "Search posters" %}</h4>
        <form method="get" action="{% url 'posters_app:home' %}">
            {{ form.query.label_tag }}
            {{ form.query }}
            <button type="submit">{% trans "Search" %}</button>
        </form>
    </div>
    <div class="container-fluid" id="main-grid">
        <!-- ROW 1 -->
        {% for poster in page_obj %}
            {% if forloop.counter0|divisibleby:3 %}
                <div class="row">
            {% endif %}
            <div class="col-md-4">
                <div class="thumbnail">
                    <a href="{% url 'posters_app:poster_view' poster.id %}">
                        <img src="{% url 'posters_app:get_image_by_image_id' poster.image_ids.0 %}" alt="Image">
                        <div class="caption">
                            <h4><b>{{ poster.header }}</b></h4>
                            <h5>{{ poster.price_rounded }} {{ poster.currency }}</h5>
                            <h6>{{ poster.created }}</h6>
                        </div>
                    </a>
                </div>

                {% comment %} <div class="media">
                    <a class="d-flex align-self-center" href="{% url 'posters_app:poster_view' poster.id %}">
                        <img src="{% url 'posters_app:get_image_by_image_id' poster.image_ids.0 %}" alt="Image">
                    </a>
                    <div class="media-body">
                        <h3>{{ poster.header }}</h3>
                        <p>{{ poster.price_rounded }} {{ poster.currency }}</p>
                        <p>{{ poster.created }}</p>
                    </div>
                </div> {% endcomment %}
            </div>
            {% if forloop.counter0|add:1|divisibleby:3 or forloop.last %}
                </div>
            {% endif %}

        {% endfor %}
    </div>
    <div class="pagination">
        <ul class="pagination">
            <!-- "First" page link -->
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo; first</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">&laquo; first</a>
                </li>
            {% endif %}
    
            <!-- Previous page link -->
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">previous</a>
                </li>
            {% endif %}
    
            <!-- Page numbers -->
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active">
                        <a class="page-link" href="#">{{ num }}</a>
                    </li>
                {% elif num > page_obj.number|add:'-5' and num < page_obj.number|add:'5' %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                    </li>
                {% endif %}
            {% endfor %}
    
            <!-- Next page link -->
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">next</a>
                </li>
            {% endif %}
    
            <!-- "Last" page link -->
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">last &raquo;</a>
                </li>
            {% endif %}
        </ul>
    </div> 
</div>



{% comment %} 

{% for row in recommended_posters_row %}
<div class="row">
 {% for poster in row %}
     <div class="col-md-4">
         <div class="media">
             <a class="d-flex align-self-center" href="{% url 'posters_app:poster_view' poster.id %}">
                 <img src="{% url 'posters_app:get_image_by_image_id' poster.image_ids.0 %}" alt="Image">
             </a>
             <div class="media-body">
                 <h3>{{ poster.header }}</h3>
                 <p>{{ poster.price_rounded }} {{ poster.currency }}</p>
             </div>
         </div>
     </div>
 {% endfor %}
</div>
{% endfor %} 


{% endcomment %}




{% comment %} <h1>Hello Posters App</h1>
<div>
    <ul>
        {% for poster in recommended_posters %}
            <li>
                <div id="poster">
                    <h3 id="posterHeader"> {{ poster.header }} </h3>
                    <h4>Poster id: {{ poster.id }}</h4>
                    <a href="{% url 'posters_app:poster_view' poster.id %}"> About Poster </a>
                    <p id="posterDescription"> {{ poster.description }} </p>
                    <p id="posterDescription"> {{ poster.status }} </p>
                    <p id="posterDescription"> {{ poster.formatted_created }} </p>
                    <p id="posterPhonenumber"> {{ poster.phone_number }} </p>
                    <p id="posterEmail"> {{ poster.email }} </p>
                    <p id="posterPrice"> {{ poster.price_rounded }} </p>
                    <p id="posterCurrnecy"> {{ poster.currency }} </p>
                    {% for image_id in poster.image_ids%}
                        <img src="{% url 'posters_app:get_image_by_image_path' image_id %}" alt="Image">
                    {% endfor %}
                </div>
                
            </li>
        {% endfor %}
    </ul>
</div> {% endcomment %}
{% comment %} {% for image in images %}
        <h1>{{ image.image_path }}</h1>
        <img src="{% url 'posters_app:get_image_by_image_id' image.id %}" alt="Image">
{% endfor %} {% endcomment %}

{% endblock %}

posters/posters_app/templates/posters_app/poster.html
{% extends 'posters_base.html' %}
{% load i18n %}
{% block title %} {% trans "Poster info" %}  {% endblock %}

{% block content %}
{% load static %}
{% load custom_filters %}
<link rel="stylesheet" href="{% static 'posters_app/css/poster.css'%}">
<script src="{% static 'posters_app/js/poster.js'%}" type="text/javascript"></script>

<!-- Swiper CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.css"/>

<!-- Swiper JS -->
<script src="https://cdn.jsdelivr.net/npm/swiper@10/swiper-bundle.min.js"></script> 

<!-- Flickity CSS -->
{% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flickity@3/dist/flickity.min.css">

<!-- Flickity JS -->
<script src="https://cdn.jsdelivr.net/npm/flickity@3/dist/flickity.pkgd.min.js"></script> {% endcomment %}


<div class="container">
    {% if poster.owner == user %}
    <div class="panel panel-info">
        <div class="panel-heading"><p>{% trans "Manage your poster" %}</p></div>
        <div class="panel-body">
            <form action="{% url 'posters_app:delete_poster_by_id' poster_id=poster.id %}" method="post" style="display:inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this poster?');"> {% trans "Delete Poster" %}</button>
            </form>
            <button type="button" class="btn btn-primary"><a style="color: white;" href="{% url 'posters_app:edit_poster' poster.id %}">{% trans "Edit poster" %} </a></button>    
        </div>
    </div>
    {% endif %}
    <div class="container">
        <h1 id="poster-header">{{ poster.header }}</h1>
    </div>
    <div class="container" id="container-price">
        <h3>{{ poster.price_rounded }} {{ poster.currency }}</h3>
    </div>


    {% comment %} <div class="carousel">
        {% for image_id in poster.image_ids %}
            <div class="carousel-cell">
                <img src="{% url 'posters_app:get_image_by_image_id' image_id %}" alt="Image {{ forloop.counter }}">
            </div>
        {% endfor %}
    </div> {% endcomment %}


    <section class="container">
        <div class="slider-wrapper">
            <div class="slider">

            {% for image_id in poster.image_ids %}
                    <img id="slide-{{forloop.counter }}" src="{% url 'posters_app:get_image_by_image_id' image_id %}" alt="Image">
                    {% comment %} <img id="slide-{{forloop.counter }}" src="{{ image.id|build_safe_image_url_by_image_id }}" alt="Image"> {% endcomment %}
            {% endfor %}
            </div>
            <div class="slider-nav">
                {% for image_id in poster.image_ids %}
                <a href="#slide-{{ forloop.counter }}"></a>
                {% endfor %}
            </div>
        </div>
    </section>

    <div class="container">
        <h3>{% trans "Description" %}</h3>
        <p>{{ poster.description }}</p>
    </div>
    <div class="container">
        <h3>{% trans "Contact information" %}</h3>
        <ul>
            <li> <i class="fa fa-phone" aria-hidden="true"></i> {{ poster.phone_number }}</li>
            <li> <i class="fa fa-envelope-o" aria-hidden="true"></i> {{ poster.email }}</li>
        </ul>
    </div>
    <div class="container"> 
        <h5>{% trans "See other posters in this category" %}</h5>
        <a href="{% url 'posters_app:list_posters_in_category' poster.category %}"> {{ poster.category }} </a>
    </div>
</div>


{% comment %} <script>
    var elem = document.querySelector('.carousel');
    var flkty = new Flickity(elem, {
        cellAlign: 'left',
        contain: true,
        wrapAround: true,   // Enable looping
        autoPlay: 3000,     // Auto-play every 3 seconds
        adaptiveHeight: true // Adjust height based on the slide content
    });
</script> {% endcomment %}



{% comment %} <script>
    var swiper = new Swiper('.swiper-container', {
        loop: true,             // Enable looping
        pagination: {
            el: '.swiper-pagination',
            clickable: true
        },
        navigation: {
            nextEl: '.swiper-button-next',
            prevEl: '.swiper-button-prev'
        },
        autoHeight: true        // Adjust container height based on slide content
    });
</script> {% endcomment %}
    

{% comment %} <script>
    let currentIndex = 0;

    function moveSlide(direction) {
        const carouselContainer = document.querySelector('.carousel-container');
        const items = document.querySelectorAll('.carousel-item');
        const totalItems = items.length;

        currentIndex = (currentIndex + direction + totalItems) % totalItems;
        carouselContainer.style.transform = `translateX(-${currentIndex * 100}%)`;
    }
</script> {% endcomment %}



{% endblock %}

posters/posters_app/templates/posters_app/poster_old.html
{% extends 'posters_base.html' %}

{% block title %} Poster info  {% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'posters_app/css/poster.css'%}">
<script src="{% static 'posters_app/js/poster.js'%}" type="text/javascript"></script>

<div id="poster" csrf-token="{{ csrf_token }}">
    <h3 id="posterHeader"> {{ poster.header }} </h3>
    <p id="posterDescription"> {{ poster.description }} </p>
    <p id="posterDescription"> {{ poster.status }} </p>
    <p id="posterDescription"> {{ poster.formatted_created }} </p>
    <p id="posterPhonenumber"> {{ poster.phone_number }} </p>
    <p id="posterEmail"> {{ poster.email }} </p>
    <p id="posterPrice"> {{ poster.price_rounded }} </p>
    <p id="posterCurrnecy"> {{ poster.currency }} </p>
    <p id="posterCurrnecy"> {{ poster.category_name }} </p>
    {% for image_id in poster.image_ids %}
        <img src="{% url 'posters_app:get_image_by_image_id' image_id %}" alt="Image">
    {% endfor %}
    <form action="{% url 'posters_app:delete_poster_by_id' poster_id=poster.id %}" method="post" style="display:inline;">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this poster?');">Delete Poster</button>
    </form>
    <a href="{% url 'posters_app:edit_poster' poster.id %}">Edit poster </a>

<script>
    // {% comment %} var posterData = {{ csrf_token|json_script:"csrf_token" }}; {% endcomment %}
</script>
{% endblock %}