posters/posters/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.conf import settings
import debug_toolbar
# NOTE: Add in production!
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    # NOTE: Uncomment in production!
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    # path('posters/', include(('posters_app.urls', 'posters_app'), namespace='posters_app')),
    # path('user_account/', include(('user_account_app.urls', 'user_account_app'), namespace='user_account_app')),
    path('i18n/', include('django.conf.urls.i18n')),
    # path('user_auth/', include("django.contrib.auth.urls")),
]


urlpatterns += i18n_patterns (
    path('posters/', include(('posters_app.urls', 'posters_app'), namespace='posters_app')),
    path('user_account/', include(('user_account_app.urls', 'user_account_app'), namespace='user_account_app')),
)

# NOTE: Comment in Production!
if settings.DEBUG:
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

posters/posters_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('categories/', views.PosterCategoriesView.as_view(), name='categories'),
    path('all/<str:category_name>', views.CategoryView.as_view(), name='list_posters_in_category'),
    path('create_poster/', views.create_poster, name='create_poster'),
    path('poster/<int:poster_id>/edit', views.edit_poster, name='edit_poster'),
    path('poster/<int:poster_id>/delete', views.delete_poster_by_id, name='delete_poster_by_id'),
    path('user_posters/<int:user_id>', views.create_poster, name='user_posters'),
    path('poster/<int:poster_id>', views.PosterView.as_view(), name='poster_view'),
    path('get_poster_image/<slug:image_id>', views.get_image_by_image_id, name='get_image_by_image_id'),
    # path('get_poster_image/', views.get_image_by_image_id, {'image_id': None}, name='get_default_image'),
    path('get_poster_image/<path:image_path>', views.get_image_by_image_path, name='get_image_by_image_path')
]

posters/user_account_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("sign_up", views.user_sign_up, name='user_sign_up'),
    path("email_login", views.email_login, name='user_email_login'),
    path("email_login_code_verification", views.email_login_verification, name='user_email_login_code_verification'),
    path("profile_edit", views.user_profile_edit, name='user_profile_edit'),
    path("view_account", views.view_user_account, name='view_user_account'),
    path("deactivate_user", views.deactivate_user, name='deactivate_user_account'),
    path("delete_user", views.delete_user, name='delete_user_account'),
    path("user_logout", views.user_logout, name='user_logout'),
]

#NOTE: Now default URLs for password change, password_reset, etc..

posters/templates/posters_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>{% block title %} Posters Project Base {% endblock %}</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    

    {% load static %}
    {% load i18n %}
    {% load custom_filters %}
</head>
<body>
  <link rel="stylesheet" href="{% static 'css/posters_base.css' %}">
  <script src="{% static '/js/posters_base.js' %}" type="text/javascript"></script>



  <div class="wrapper">
    {% block header %}
    <header>
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
              <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'posters_app:home' %}">Posters</a>
            </div>
              <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'posters_app:home' %}">{% trans "Home" %}</a></li>
                <li><a href="{% url 'posters_app:categories' %}">{% trans "Categories" %}</a></li>
                <li><a id="create-poster-link" href="{% url 'posters_app:create_poster' %}">{% trans "Create poster" %}</a></li>
                <li class="nav-item dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% trans "Languages" %} <span class="caret"></span></a>
                  <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% for lang in languages %}
                    <li>
                      <a class="dropdown-item" href="/{{ lang.code }}{{ request.get_full_path|slice:'3:' }}">
                        {{ lang.name_local }}
                      </a>
                    </li>
                    {% endfor %}
                  </ul>
                </li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li><a href="{% url 'user_account_app:view_user_account' %}"><span class="glyphicon glyphicon-user"></span> {% trans "Profile" %}</a></li>
                {% else %}
                {% comment %} <li><a href="{% url 'user_account_app:user_sign_up' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li> {% endcomment %}
                <li><a href="{% url 'user_account_app:user_email_login' %}"><span class="glyphicon glyphicon-log-in"></span> {% trans "LogIn" %}</a></li>
                {% endif %}
              </ul>
            </div>
          </nav>

    </header>
    {% endblock %}
    
    <main>
      {% block content %}
      <h1>Poster Project Base HTML Page!</h1>
      {% endblock %}
    </main>
    
    {% block footer %}
    <footer class="bg-dark text-center text-lg-start text-white">
      <a href="https://chabrovs.tech">
        <div class="well well-sm">
          {% trans "Developer" %}
        </div>
      </a>
      <a href="https://github.com/chabrovs/posters">
        <div class="well well-sm">
          {% trans "View source code" %}
        </div>
      </a>
    </footer>
    {% endblock %}
  </div>


</body>
</html>

<!-- Latest compiled and minified CSS -->


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<!-- <script src="jquery-3.7.1.min.js"></script> -->