posters/posters/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, re_path
from django.conf import settings
import debug_toolbar
# NOTE: Add in production!
from django.conf.urls.static import static
from django.views.static import serve
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    # NOTE: Uncomment in production!
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    # path('posters/', include(('posters_app.urls', 'posters_app'), namespace='posters_app')),
    # path('user_account/', include(('user_account_app.urls', 'user_account_app'), namespace='user_account_app')),
    path('i18n/', include('django.conf.urls.i18n')),
    # path('user_auth/', include("django.contrib.auth.urls")),
]


urlpatterns += i18n_patterns (
    path('posters/', include(('posters_app.urls', 'posters_app'), namespace='posters_app')),
    path('user_account/', include(('user_account_app.urls', 'user_account_app'), namespace='user_account_app')),
)

# NOTE: Comment in Production!
if settings.DEBUG:
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += [
        re_path(r'^rosetta/', include('rosetta.urls'))
    ]

posters/posters_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('categories/', views.PosterCategoriesView.as_view(), name='categories'),
    path('all/<str:category_name>', views.CategoryView.as_view(), name='list_posters_in_category'),
    path('create_poster/', views.create_poster, name='create_poster'),
    path('poster/<int:poster_id>/edit', views.edit_poster, name='edit_poster'),
    path('poster/<int:poster_id>/delete', views.delete_poster_by_id, name='delete_poster_by_id'),
    path('user_posters/<int:user_id>', views.create_poster, name='user_posters'),
    path('poster/<int:poster_id>', views.PosterView.as_view(), name='poster_view'),
    path('get_poster_image/<slug:image_id>', views.get_image_by_image_id, name='get_image_by_image_id'),
    # path('get_poster_image/', views.get_image_by_image_id, {'image_id': None}, name='get_default_image'),
    path('get_poster_image/<path:image_path>', views.get_image_by_image_path, name='get_image_by_image_path')
]

posters/user_account_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("sign_up", views.user_sign_up, name='user_sign_up'),
    path("email_login", views.email_login, name='user_email_login'),
    path("email_login_code_verification", views.email_login_verification, name='user_email_login_code_verification'),
    path("profile_edit", views.user_profile_edit, name='user_profile_edit'),
    path("view_account", views.view_user_account, name='view_user_account'),
    path("deactivate_user", views.deactivate_user, name='deactivate_user_account'),
    path("delete_user", views.delete_user, name='delete_user_account'),
    path("user_logout", views.user_logout, name='user_logout'),
]

#NOTE: Now default URLs for password change, password_reset, etc..

posters/user_account_app/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .business_logic.auth_logic import EmailVerification


class CustomUserCreatingForm(UserCreationForm):
    # email = forms.EmailField(required=False, help_text="Not required")
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


class UserProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class EmailLogInForm(forms.Form):
    email = forms.EmailField(max_length=120, widget=forms.EmailInput(attrs={
        "placeholder": "your email"
    }))

    def send_verification_code(self) -> None:
        EmailVerification.send_code(email=self.cleaned_data['email'])


class EmailLogInCodeVerificationForm(forms.Form):
    email = forms.EmailField(
        max_length=120,
        widget=forms.EmailInput(
            attrs={
                "readonly": "readonly"
            }))
    client_code = forms.CharField(max_length=120, widget=forms.TextInput(
        attrs={"placeholder": "Enter your code from email"}))

posters/user_account_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CustomUserCreatingForm, UserProfileUpdateForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import logout, login
from .forms import EmailLogInForm, EmailLogInCodeVerificationForm
from .business_logic.auth_logic import Auth
from posters_app.business_logic.view_logic import FrequentQueries
import logging
from django.utils import translation

logger = logging.getLogger(__name__)
# Create your views here.


def set_language(request):
    user_language = request.GET.get('language', 'en')
    translation.activate(user_language)
    request.session[translation.LANGUAGE_SESSION_KEY] = user_language
    return redirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def view_user_account(request):
    template_name = 'user_account_app/user_account_view.html'
    user_fields = [
        (field.name, getattr(request.user, field.name)) for field in request.user._meta.fields]
    context = {
        "user_fields": user_fields,
        "users_posters": FrequentQueries.get_users_posters(user_id=request.user.id)
    }
    return render(request, template_name, context)


@login_required
def user_profile_edit(request):
    if request.method == "POST":
        form = UserProfileUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, "You profile has been updated successfully!")
            return redirect('user_account_app:view_user_account')
    else:
        form = UserProfileUpdateForm(instance=request.user)

    return render(request, 'user_account_app/user_account_edit.html', {"form": form})


def user_sign_up(request):
    if request.method == 'POST':
        form = CustomUserCreatingForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect('user_account_app:view_user_account')
    else:
        form = CustomUserCreatingForm()

    return render(request, 'user_account_app/user_sign_up.html', {'form': form})


def email_login(request):
    if request.method == "POST":
        form = EmailLogInForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            request.session['user_email'] = email
            Auth.send_verification('email', email)
            return redirect("user_account_app:user_email_login_code_verification")
    else:
        form = EmailLogInForm()
    return render(request, 'user_account_app/user_account_email_login.html', {"form": form})


def email_login_verification(request):
    if request.method == "POST":
        form = EmailLogInCodeVerificationForm(request.POST)
        if form.is_valid():
            if Auth.verify_user("email", form.cleaned_data['email'], form.cleaned_data['client_code']):
                user, created = User.objects.get_or_create(email=form.cleaned_data['email'])
                if created:
                    logger.debug(f"User is being created for {form.cleaned_data['email']}")
                login(request, user)
                return redirect('user_account_app:view_user_account')
            else:
                messages.error(request, "Wrong password or email!")
                return redirect("user_account_app:user_email_login_code_verification")
        else:
            messages.error(request, "Please correct error bellow")
    else:
        email = request.session.get('user_email', None)
        form = EmailLogInCodeVerificationForm(initial={"email": email})
    return render(request, 'user_account_app/user_account_email_login_verification.html', {"form": form})


@login_required
def deactivate_user(request):
    if request.method == "POST":
        user = request.user
        user.is_active = False
        user.save()
        return redirect("posters_app:home")


@login_required
def delete_user(request):
    if request.method == "POST":
        user = request.user
        user.delete()
        return redirect('posters_app:home')


@login_required
def user_logout(request):
    if request.method == "POST":
        logout(request)
        return redirect('posters_app:home')
    

posters/user_account_app/templates/user_account_app/user_account_edit.html
{% extends 'posters_base.html' %}
{% load i18n %}
{% block title %} {% trans "Edit profile" %} {% endblock %}


{% block content %}
{% load crispy_forms_tags %}
{% load static %}

<div class="container">
  <h2>{% trans "Edit profile" %}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit">{% trans "Update profile" %}</button>
    <p>{% trans "back to profile" %} <a href="{% url 'user_account_app:view_user_account' %}">{% trans "Go back" %}</a> </p>
  </form>
</div>



{% endblock %}

posters/user_account_app/templates/user_account_app/user_account_email_login.html
{% extends 'posters_base.html' %}
{% load i18n %}

{% block title %} {% trans "LogIn" %} {% endblock %}

{% block content %}
{% load crispy_forms_tags %}
{% load static %}
<link rel="stylesheet" href="{% static 'user_account_app/css/user_sign_up.css' %}">
<script src="{% static 'user_account_app/js/user_sign_up.js' %}" type="text/javascript"></script>

<div class="container sm">
    <h2>{% trans "LogIn by email." %}</h2>
    <form action="{% url 'user_account_app:user_email_login' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">{% trans "get code" %}</button>
    </form>
</div>

{% endblock %}

posters/user_account_app/templates/user_account_app/user_account_email_login_verification.html
{% extends 'posters_base.html' %}
{% load i18n %}
{% block title %} {% trans "Code confirmation" %} {% endblock %}

{% block content %}
{% load crispy_forms_tags %}
{% load static %}
<link rel="stylesheet" href="{% static 'user_account_app/css/user_sign_up.css' %}">
<script src="{% static 'user_account_app/js/user_sign_up.js' %}" type="text/javascript"></script>

<div class="container sm">
    <h2>{% trans "Verify code" %}</h2>
    <form action="{% url 'user_account_app:user_email_login_code_verification' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">{% trans "Enter" %}</button>
    </form>
</div>

{% endblock %}

posters/user_account_app/templates/user_account_app/user_account_view.html
{% extends 'posters_base.html' %}
{% load i18n %}
{% block title %} {{ user.username }} {% endblock %}

{% block content %}
{% load crispy_forms_tags %}
{% load static %}
<link rel="stylesheet" href="{% static 'user_account_app/css/user_account_view.css' %}">


<div class="container">
    <div class="container">
        <h2>{%trans "Hello" %} {{ user.first_name }} </h2>
        <h4>{% trans "Account information: " %}</h4>
        <ul>
        {% for key, value in user_fields %}
            <li> <p> <b>{{ key|capfirst }}</b> | {{ value }}</p>  </li>
        {% endfor %}
        </ul>
    </div>
    
    <div class="panel panel-primary">
        <div class="panel-heading">{% trans "My posters" %}</div>
        <div class="panel-body">
            <div class="list-group">
                {% for poster in users_posters %}
                <a href="{% url 'posters_app:poster_view' poster.id %}" class="list-group-item">{{ poster.header }}</a>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="panel panel-info">
        <div class="panel-heading">Account management</div>
        <div class="panel-body">
            <form method="post" action="{% url 'user_account_app:user_logout' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">{%trans "LogOut" %}</button>
            </form>
    
            <p>{% trans "Edit profile" %} <a href="{% url 'user_account_app:user_profile_edit' %}">{% trans "Edit" %}</a> </p>

            <form method="post" action="{% url 'user_account_app:deactivate_user_account' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-warning" onclick="return confirm('Are you sure you want to delete this poster?');">{%trans "Deactivate" %}</button>
            </form>

            <form method="post" action="{% url 'user_account_app:delete_user_account' %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this poster?');";>{% trans "Delete" %}</button>
            </form>
        </div>
      </div>
</div>

{% endblock %}

posters/user_account_app/templates/user_account_app/user_sign_up.html
{% extends 'posters_base.html' %}

{% block title %} SingUp {% endblock %}

{% block content %}
{% load crispy_forms_tags %}
{% load static %}
<link rel="stylesheet" href="{% static 'user_account_app/css/user_sign_up.css' %}">
<script src="{% static 'user_account_app/js/user_sign_up.js' %}" type="text/javascript"></script>

<div class="container sm">
    <form action="{% url 'user_account_app:user_sign_up' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success">SignUp</button>
    </form>
    <p>Already have an account ? <a href="{% url 'login' %}">LogIn</a></p>
</div>

{% endblock %}